version: '3.2'
services:
  sonarqube:
    build:
      context: sonarqube/
    ports:
      - 9111:9000
      - 9192:9092
    container_name: sonarqube
    networks:
      - back
  jenkins:
    build:
      context: jenkins/
    privileged: true
    user: root
    ports:
      - 8282:8080
      - 51111:50000
    container_name: jenkins
    volumes:
      - /Users/natemoran/docker/jenkins-pipeline/jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - sonarqube
    networks:
      - back

networks:
  back:
    driver: bridge
